### ISSUE TITLE
Reportage coiffeurs blagueurs

### ISSUE THREAD

**Issue by ElioProphette** [tifhair/tifhair-website#1]
Bonjour @tifhair , je souhaiterai écrire un article sur votre carte pour le journal le Progrès. J'ai remarquer que le département de la Haute-Loire, que nous couvrons, est deuxième en terme de proportion.  Est-ce que vous seriez disponible pour répondre à quelques questions , Vous pouvez me contacter via elio.prophete@leprogres.fr

**Comment by tifhair** [comment]
Suivi via DM twitter.
